### ISSUE TITLE
Can't download the data from google drive

### ISSUE THREAD

**Issue by peterwu19881230** [sigven/oncoEnrichR#28]
**Can't download the data from google drive**

Hi, dear developers:

Nice and promising package. When I was trying to run it, the first step (download database from google drive) failed. Might giving some help?

Sincerely,
Peter 

*The error message:*
```
INFO  [2022-10-04 09:06:59] Downloading remote oncoEnrichR dataset from Google Drive to cache_dir
Error in `googledrive::drive_download()`:
! Download failed.
Run `rlang::last_error()` to see where the error occurred.
> rlang::last_error()
<error/rlang_error>
Error in `googledrive::drive_download()`:
! Download failed.
---
Backtrace:
 1. oncoEnrichR::load_db("~/Downloads/")
 5. googledrive::drive_download(fname_gd, path = fname_local, overwrite = TRUE)
Run `rlang::last_trace()` to see the full context.
> rlang::last_trace()
<error/rlang_error>
Error in `googledrive::drive_download()`:
! Download failed.
---
Backtrace:
    ▆
 1. └─oncoEnrichR::load_db("~/Downloads/")
 2.   ├─googledrive::with_drive_quiet(...)
 3.   │ └─withr::with_options(list(googledrive_quiet = TRUE), code = code)
 4.   │   └─base::force(code)
 5.   └─googledrive::drive_download(fname_gd, path = fname_local, overwrite = TRUE)
 6.     └─googledrive:::drive_abort("Download failed.")
 7.       └─cli::cli_abort(message = message, ..., .envir = .envir)
 8.         └─rlang::abort(...)

```

**Comment by sigven** [comment]
Hey Peter!

Thanks for trying out oncoEnrichR. I just played a bit with this myself as well (using v1.3.2), and while I was succeeding at first, I eventually ran into a download error like the one you encountered. Sorry about this, I have not completely figured out what's the underlying cause yet. I _suspect_ it might be related to a Google download limitation (many users accessing the same file will eventually prevent access within a 24 hour window, from what I have read online). Before I figure out a solution without such download restrictions, I have placed the whole oncoEnrichR data repository (v1.3.2, make sure you are running the latest version) for you here:

[oedb_v1.3.2.rda](https://insilico.hpc.uio.no/oncoEnrichR/oedb_v1.3.2.rda)

Essentially, rather than running the `load_db` command, you should now:
1. Download the `oedb_v1.3.2.rda` file to your local computer using the link above, and 
2. Load the RDA file in your R session, i.e.`load(file = "~/Downloads/oedb_v1.3.2.rda")` - this will gove you a `oedb` object that you can pass as the value for the `oeDB` argument in`onco_enrich` and `write` functions. 

Please let me know how it works!

kind regards,
Sigve

**Comment by sigven** [comment]
Btw @jeffreyhanson (somewhat related to https://github.com/eblondel/zen4R/issues/98): got any experience with downloads from Google Drive using `googledrive` package? I am a bit puzzled by the inconsistent success in downloading success and download fails.

**Comment by jeffreyhanson** [comment]
No idea sorry, I've never used the googledrive package.

**Comment by sigven** [comment]
@peterwu19881230 I have made some new attempts tonight with `oncoEnrichR::load_db()`, successfully retrieving the data. I would recommend you try to repeat the call to `load_db()`, and see if the error persists or not.

**Comment by peterwu19881230** [comment]
Hi, dear @sigven  and @jeffreyhanson:
Thanks for helping. Sorry I was swamped by many other projects and finally got here again.
While there's still that google drive issue, I tested the provided rdb file and was able to get the result from your demo 👍

Merry Christmas,
Peter
